language: ruby
sudo: false

notifications:
  email: false

rvm:
  - 2.5.3
  - 2.6.0

notifications:
  irc: "irc.freenode.org#blacklight"
  email:
      - blacklight-commits@googlegroups.com

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

jdk: openjdk11
